---
title: "Assignment 05"
author: "Nick Stabile"
date: "10/8/2020"
output: html_document
---
# Todo: Write an informative README.md file

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(stringr)
library(lubridate)
library(sf)
library(gridExtra)
```

## Data Loading & Cleaning

```{r}

dc_permits_2020 <- 
  read_csv("data/Building_Permits_in_2020.csv", 
                            col_type = cols(
                              LATITUDE = col_character(),
                              LONGITUDE = col_character()
                            )) %>% 
  rename_with(tolower) %>% 
  mutate(address_id = as.character(maraddressrepositoryid))

```

## Filtering data to construction permits within six months of today

```{r}

dc_permits_recent_construction <- dc_permits_2020 %>% 
  filter(!is.na(latitude) & !is.na(longitude)) %>% 
  filter(permit_type_name == "CONSTRUCTION") %>% 
  filter(issue_date > today() - months(6))

table(month(dc_permits_recent_construction$issue_date))
min(dc_permits_recent_construction$issue_date)

```
##  Convert Lat/Lon to Points Geometry

```{r}

dc_permits_recent_construction <- st_as_sf(
  dc_permits_recent_construction,
  coords = c("longitude", "latitude"),
  crs = 4326,
  remove = FALSE)

ggplot(data = dc_permits_recent_construction) +
  geom_sf(aes(color = permit_subtype_name == "NEW BUILDING")) +
  scale_colour_manual(name = 'New Building', values = setNames(c('blue','red'),c(T, F))) +
  theme_void()

```

##  Load Census Tracts, Perform a Spatial Join, and Create Choropleth

```{r}

dc_tracts <- st_read("data/Census_Tracts_in_2010.shp") %>% 
  select(TRACT, GEOID, geometry)

ggplot() +
  geom_sf(data = dc_tracts)


# Permit data doesn't have tract or geoID information, adding additional data source
dc_addresses <- st_read("data/Address_Points.csv") %>% 
  select(address_id = ADDRESS_ID, TRACT = CENSUS_TRACT)

dc_permits_recent_construction <- 
  left_join(dc_permits_recent_construction, dc_addresses, by = "address_id")

dc_permits_merged <- st_join(
  dc_permits_recent_construction, # points
  dc_tracts, # polygons
  join = st_within
)

dc_permits_merged <- st_set_geometry(dc_permits_merged, NULL)
dc_permits_agg <- dc_permits_merged %>%
  group_by(GEOID) %>%
  summarize(
    num_new = sum(permit_subtype_name == "NEW BUILDING"),
    permit_count = n(),
    rate_new = num_new/permit_count
  )

dc_permits_agg <- dc_tracts %>%
  left_join(dc_permits_agg, by = "GEOID")

ggplot(data = dc_permits_agg) +
  geom_sf(aes(fill = permit_count, color = rate_new)) + 
  scale_color_distiller(palette = "YlGnBu") +
  theme_void()

```

